# Generated by Django 5.0.6 on 2024-08-10 04:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.TextField()),
                ('des', models.TextField(verbose_name='Descripcion del curso')),
                ('costo', models.CharField(max_length=15)),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('acti', models.TextField(verbose_name='Nombre de la Actividad')),
                ('descripcionAct', ckeditor.fields.RichTextField(verbose_name='Descripción de la actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
