# Generated by Django 5.0.6 on 2024-08-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='calificacion',
            field=models.CharField(default='N/A', max_length=5, verbose_name='Calificación'),
            preserve_default=False,
        ),
    ]
