# Generated by Django 5.0.6 on 2024-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_cursos_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='aprendizaje',
            field=models.TextField(default='Sin informacion', verbose_name='Lista de aprendizaje'),
            preserve_default=False,
        ),
    ]
