# Generated by Django 5.0.6 on 2024-08-13 21:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_cursos_aprendizaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='aprendizaje',
            field=ckeditor.fields.RichTextField(verbose_name='Lista de aprendizaje'),
        ),
    ]
