# Generated by Django 5.0.6 on 2024-08-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_cursos_aprendizaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='inscritos',
            field=models.IntegerField(default=0),
        ),
    ]
