# Generated by Django 5.0.6 on 2024-08-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_mensajeuser_delete_actividad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensajeUser',
        ),
    ]
