# Generated by Django 5.0.6 on 2024-08-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_delete_mensajeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='preInscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('correo', models.TextField(verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Pre-Inscripciones',
                'verbose_name_plural': 'Pre-Inscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
