# Generated by Django 5.0.6 on 2024-08-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_preinscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='curso',
            field=models.TextField(default='N/A', verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
