# Generated by Django 5.0.6 on 2024-08-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_preinscripcion_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preinscripcion',
            options={'ordering': ['-created'], 'verbose_name': 'Pre-Inscripción', 'verbose_name_plural': 'Pre-Inscripciones'},
        ),
    ]
